spring:
  application:
    name: embabel-webapp-demo

embabel:
  models:
    default-llm: deepseek-r1:8b
    llms:
      better: llama3.2:latest
      cheaper: deepseek-r1:8b
      faster: ai/smollm2:360M-Q4_K_M

logging:
  level:
    com:
      embabel: DEBUG